using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Stitch.Generator;

internal static class Emitter
{
    private static readonly Regex RouteTokenPattern = new(@"\{(\w+)\}", RegexOptions.Compiled);

    public static void Emit(SourceProductionContext ctx, ClientModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Net;");
        sb.AppendLine("using System.Net.Http;");
        sb.AppendLine("using System.Net.Http.Headers;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Stitch.Core;");
        foreach (var u in model.Usings)
            sb.AppendLine($"using {u};");

        sb.AppendLine();

        var hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {model.Namespace}");
            sb.AppendLine("{");
        }

        var indent = hasNamespace ? "    " : "";
        sb.AppendLine($"{indent}internal sealed class {model.ImplementationName} : {model.InterfaceName}");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    private readonly HttpClient _http;");
        sb.AppendLine($"{indent}    private readonly StitchOptions _opts;");
        sb.AppendLine();
        sb.AppendLine($"{indent}    public {model.ImplementationName}(HttpClient http, StitchOptions opts)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        _http = http;");
        sb.AppendLine($"{indent}        _opts = opts;");
        sb.AppendLine($"{indent}    }}");

        foreach (var method in model.Methods)
        {
            sb.AppendLine();
            EmitMethod(sb, method, indent + "    ");
        }

        sb.AppendLine($"{indent}}}");

        if (hasNamespace)
            sb.AppendLine("}");

        ctx.AddSource(
            $"{model.ImplementationName}.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitMethod(StringBuilder sb, MethodModel method, string indent)
    {
        var signature = BuildSignature(method);
        sb.AppendLine($"{indent}public async {signature}");
        sb.AppendLine($"{indent}{{");

        var ctParam = method.Parameters
            .FirstOrDefault(p => p.Source == BindingSource.CancellationToken);
        var ctArg = ctParam?.Name ?? "default";

        var url = BuildUrl(method, sb, indent + "    ");

        sb.AppendLine($"{indent}    using var __req = new HttpRequestMessage(HttpMethod.{method.Verb}, {url});");

        if (method.IsMultipart)
            EmitMultipartContent(sb, method, indent + "    ");
        else
        {
            var bodyParam = method.Parameters.FirstOrDefault(p => p.Source == BindingSource.Body);
            if (bodyParam != null)
                sb.AppendLine($"{indent}    __req.Content = _opts.Serializer.Serialize({bodyParam.Name});");
        }

        foreach (var p in method.Parameters.Where(p => p.Source == BindingSource.Header))
        {
            var value = p.IsNullable
                ? $"{p.Name}?.ToString()"
                : $"{p.Name}.ToString()";
            sb.AppendLine($"{indent}    if ({p.Name} != null) __req.Headers.TryAddWithoutValidation(\"{p.HeaderName}\", {value});");
        }

        EmitInterceptorCalls(sb, indent + "    ", ctArg, beforeSend: true);

        sb.AppendLine($"{indent}    using var __res = await _http.SendAsync(__req, HttpCompletionOption.ResponseHeadersRead, {ctArg});");

        EmitInterceptorCalls(sb, indent + "    ", ctArg, beforeSend: false);

        if (method.IsStitchResult)
        {
            EmitStitchResultBranch(sb, method, ctArg, indent + "    ");
        }
        else if (method.IsStitchResponse)
        {
            EmitStitchResponseBranch(sb, method, ctArg, indent + "    ");
        }
        else
        {
            sb.AppendLine($"{indent}    await _opts.ErrorHandler.EnsureSuccessAsync(__res, {ctArg});");

            if (!method.IsVoid)
            {
                var innerType = ExtractInnerType(method.ReturnTypeName);
                sb.AppendLine($"{indent}    return (await _opts.Serializer.DeserializeAsync<{innerType}>(__res.Content, {ctArg}))!;");
            }
        }

        sb.AppendLine($"{indent}}}");
    }

    private static void EmitInterceptorCalls(StringBuilder sb, string indent, string ctArg, bool beforeSend)
    {
        if (beforeSend)
        {
            sb.AppendLine($"{indent}foreach (var __interceptor in _opts.Interceptors)");
            sb.AppendLine($"{indent}    await __interceptor.OnRequestAsync(__req, {ctArg});");
        }
        else
        {
            sb.AppendLine($"{indent}foreach (var __interceptor in _opts.Interceptors)");
            sb.AppendLine($"{indent}    await __interceptor.OnResponseAsync(__req, __res, {ctArg});");
        }
    }

    private static void EmitMultipartContent(StringBuilder sb, MethodModel method, string indent)
    {
        var multipartParams = method.Parameters
            .Where(p => p.Source == BindingSource.Multipart)
            .ToList();

        sb.AppendLine($"{indent}var __multipart = new MultipartFormDataContent();");
        foreach (var p in multipartParams)
        {
            var fieldName = p.MultipartName ?? p.Name;
            if (p.IsFile)
            {
                sb.AppendLine($"{indent}if ({p.Name} != null)");
                sb.AppendLine($"{indent}{{");
                if (p.TypeName == "IFormFile" || p.TypeName.EndsWith(".IFormFile"))
                {
                    sb.AppendLine($"{indent}    var __fileContent = new StreamContent({p.Name}.OpenReadStream());");
                    sb.AppendLine($"{indent}    if (!string.IsNullOrEmpty({p.Name}.ContentType))");
                    sb.AppendLine($"{indent}        __fileContent.Headers.ContentType = MediaTypeHeaderValue.Parse({p.Name}.ContentType);");
                    sb.AppendLine($"{indent}    __multipart.Add(__fileContent, \"{fieldName}\", {p.Name}.FileName);");
                }
                else
                {
                    sb.AppendLine($"{indent}    __multipart.Add(new StreamContent({p.Name}), \"{fieldName}\", \"{fieldName}\");");
                }
                sb.AppendLine($"{indent}}}");
            }
            else
            {
                if (p.IsNullable)
                    sb.AppendLine($"{indent}if ({p.Name} != null) __multipart.Add(new StringContent({p.Name}.ToString()!), \"{fieldName}\");");
                else
                    sb.AppendLine($"{indent}__multipart.Add(new StringContent({p.Name}.ToString()!), \"{fieldName}\");");
            }
        }

        sb.AppendLine($"{indent}__req.Content = __multipart;");
    }

    private static void EmitStitchResultBranch(
        StringBuilder sb, MethodModel method, string ctArg, string indent)
    {
        var vt = method.StitchResultValueType!;
        var et = method.StitchResultErrorType!;
        sb.AppendLine($"{indent}if (__res.IsSuccessStatusCode)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    var __value = await _opts.Serializer.DeserializeAsync<{vt}>(__res.Content, {ctArg});");
        sb.AppendLine($"{indent}    return StitchResult<{vt}, {et}>.Success(__value!);");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine($"{indent}var __error = await _opts.Serializer.DeserializeAsync<{et}>(__res.Content, {ctArg});");
        sb.AppendLine($"{indent}return StitchResult<{vt}, {et}>.Failure(__error!);");
    }

    private static void EmitStitchResponseBranch(
        StringBuilder sb, MethodModel method, string ctArg, string indent)
    {
        var vt = method.StitchResponseValueType!;
        sb.AppendLine($"{indent}await _opts.ErrorHandler.EnsureSuccessAsync(__res, {ctArg});");
        sb.AppendLine($"{indent}var __value = (await _opts.Serializer.DeserializeAsync<{vt}>(__res.Content, {ctArg}))!;");
        sb.AppendLine($"{indent}var __headers = new Dictionary<string, IEnumerable<string>>();");
        sb.AppendLine($"{indent}foreach (var __header in __res.Headers)");
        sb.AppendLine($"{indent}    __headers[__header.Key] = __header.Value;");
        sb.AppendLine($"{indent}if (__res.Content?.Headers != null)");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    foreach (var __header in __res.Content.Headers)");
        sb.AppendLine($"{indent}        __headers[__header.Key] = __header.Value;");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine($"{indent}return new StitchResponse<{vt}>");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    Value = __value,");
        sb.AppendLine($"{indent}    StatusCode = __res.StatusCode,");
        sb.AppendLine($"{indent}    Headers = __headers");
        sb.AppendLine($"{indent}}};");
    }

    private static string BuildUrl(MethodModel method, StringBuilder sb, string indent)
    {
        var queryParams = method.Parameters
            .Where(p => p.Source == BindingSource.Query)
            .ToList();

        var hasRoute = RouteTokenPattern.IsMatch(method.PathTemplate);

        string rawPath;
        if (hasRoute)
        {
            rawPath = RouteTokenPattern.Replace(method.PathTemplate, m =>
            {
                var token = m.Groups[1].Value;
                var param = method.Parameters.FirstOrDefault(p =>
                    string.Equals(p.Name, token, StringComparison.OrdinalIgnoreCase));
                if (param == null) return m.Value;
                return $"{{Uri.EscapeDataString({param.Name}.ToString()!)}}";
            });
        }
        else
        {
            rawPath = method.PathTemplate;
        }

        if (queryParams.Count == 0)
        {
            return hasRoute ? $"$\"{rawPath}\"" : $"\"{rawPath}\"";
        }

        sb.AppendLine($"{indent}var __q = new List<string>();");
        foreach (var qp in queryParams)
        {
            var key = qp.QueryAlias ?? qp.Name;
            var escapedKey = Uri.EscapeDataString(key);
            var valueExpr = $"Uri.EscapeDataString({qp.Name}.ToString()!)";

            if (qp.IsNullable)
                sb.AppendLine($"{indent}if ({qp.Name} != null) __q.Add(\"{escapedKey}=\" + {valueExpr});");
            else
                sb.AppendLine($"{indent}__q.Add(\"{escapedKey}=\" + {valueExpr});");
        }

        var basePart = hasRoute ? $"$\"{rawPath}\"" : $"\"{rawPath}\"";
        return $"({basePart} + (__q.Count > 0 ? \"?\" + string.Join(\"&\", __q) : \"\"))";
    }

    private static string BuildSignature(MethodModel method)
    {
        var paramList = method.Parameters.Select(p =>
        {
            var decl = $"{p.TypeName} {p.Name}";
            if (p.HasDefault)
                decl += p.Source == BindingSource.CancellationToken ? " = default" : " = default!";
            return decl;
        });

        var returnType = method.IsVoid
            ? "Task"
            : method.ReturnTypeName;

        return $"{returnType} {method.Name}({string.Join(", ", paramList)})";
    }

    private static string ExtractInnerType(string taskTypeName)
    {
        var start = taskTypeName.IndexOf('<');
        var end = taskTypeName.LastIndexOf('>');
        if (start < 0 || end < 0) return taskTypeName;
        return taskTypeName.Substring(start + 1, end - start - 1);
    }
}
